/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;
public enum AggregateType implements TEnum{
    SUM(1),
    MAX(2),
    AVG(3);

  private static final Map<Integer, AggregateType> BY_VALUE = new HashMap<Integer,AggregateType>() {{
    for(AggregateType val : AggregateType.values()) {
      put(val.getValue(), val);
    }
  }};

  private final int value;

  private AggregateType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static AggregateType findByValue(int value) { 
    return BY_VALUE.get(value);
  }
}
