/*
 * PIP Logging Level Translations
 *
 *
 */

#ifndef PIP_LOGLEVELS_H
#define PIP_LOGLEVELS_H

#define PIP_INTEGRATE_LOGLEVEL        DEBUG3
#define PIP_DETAIL_INTEGRATE_LOGLEVEL DEBUG5
#define PIP_SAMPLE_LOGLEVEL           DEBUG3
#define PIP_PRESAMPLE_LOGLEVEL        DEBUG3
#define PIP_CONF_GATHER_LOGLEVEL      DEBUG3
#define PIP_MCDB_INFO_LOGLEVEL        DEBUG3
#define PIP_INTERNALS_LOGLEVEL        DEBUG5

#endif
