OCAML_FLAGS = -g -dtypes
OPT_FLAGS   = -ccopt -O3 -nodynlink -unsafe -noassert

OCAMLCC   =ocamlc
OCAMLOPT  =ocamlopt
OCAMLMKTOP=ocamlmktop
OCAMLDEP  =ocamldep
OCAMLYACC =ocamlyacc
OCAMLLEX  =ocamllex