/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "GUICommunication_constants.h"

namespace DBToaster { namespace GuiData {

const GUICommunicationConstants g_GUICommunication_constants;

GUICommunicationConstants::GUICommunicationConstants() {
}

}} // namespace

