/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef GUICommunication_TYPES_H
#define GUICommunication_TYPES_H

#include <Thrift.h>
#include <protocol/TProtocol.h>
#include <transport/TTransport.h>



namespace DBToaster { namespace GuiData {

typedef int32_t MyInt;

}} // namespace

#endif
