CREATE STREAM R(A int, B int) FROM FILE '../dbtoaster-experiments-data/simple/tiny/r.dat' LINE DELIMITED CSV();

CREATE STREAM S(B int, C int) FROM FILE '../dbtoaster-experiments-data/simple/tiny/s.dat' LINE DELIMITED CSV();

CREATE STREAM T(C int, D int) FROM FILE '../dbtoaster-experiments-data/simple/tiny/t.dat' LINE DELIMITED CSV();

SELECT * FROM T Z5EVDGHo WHERE ((Z5EVDGHo.D <> (Z5EVDGHo.C-(Z5EVDGHo.D*(Z5EVDGHo.C/Z5EVDGHo.D)*((6-78.8)*Z5EVDGHo.C))) OR ((0 >= Z5EVDGHo.D AND Z5EVDGHo.C >= Z5EVDGHo.D AND 8 > Z5EVDGHo.C) AND (Z5EVDGHo.D = 0 AND 6 > (Z5EVDGHo.C*(Z5EVDGHo.D+Z5EVDGHo.D)))) OR ((((Z5EVDGHo.C*((Z5EVDGHo.C*0)*0)*Z5EVDGHo.D) > Z5EVDGHo.C AND ((8-(Z5EVDGHo.D*Z5EVDGHo.D*(1*Z5EVDGHo.C))) = 59.03 OR 1 <> 0) AND (NOT 88.3 = Z5EVDGHo.C)) OR 9 < (Z5EVDGHo.D-Z5EVDGHo.D) OR 10.72 = 2) AND Z5EVDGHo.C = (Z5EVDGHo.C-Z5EVDGHo.C) AND (((0+Z5EVDGHo.C)*7*Z5EVDGHo.D)*22.93*6) >= (3+Z5EVDGHo.C+Z5EVDGHo.D))) AND (Z5EVDGHo.C = Z5EVDGHo.D AND (NOT ((NOT (Z5EVDGHo.D > Z5EVDGHo.C AND 5 > 0)) AND 6 <= 2 AND ((56.94 >= Z5EVDGHo.C OR 5 = Z5EVDGHo.C) AND Z5EVDGHo.D = Z5EVDGHo.D))) AND Z5EVDGHo.D = 50.27));
