-- for i in `ls | grep .tbl | grep -v notail` ; do echo $i; cat $i | sed 's/|$//' >`basename $i .tbl`.notail.tbl; done

DROP TABLE "CUSTOMER" CASCADE;
DROP TABLE "LINEITEM" CASCADE;
DROP TABLE "NATION" CASCADE;
DROP TABLE "ORDERS" CASCADE;
DROP TABLE "PART" CASCADE;
DROP TABLE "PARTSUPP" CASCADE;
DROP TABLE "REGION" CASCADE;
DROP TABLE "SUPPLIER" CASCADE;

CREATE TABLE "REGION"
(
  "R_REGIONKEY" integer NOT NULL,
  "R_NAME" character(25),
  "R_COMMENT" character varying(152)
--  CONSTRAINT "REGION_pkey" PRIMARY KEY ("R_REGIONKEY")
)
WITH (OIDS=FALSE);

CREATE TABLE "NATION"
(
  "N_NATIONKEY" integer NOT NULL,
  "N_NAME" character(25),
  "N_REGIONKEY" integer,
  "N_COMMENT" character(152)
--  CONSTRAINT "NATION_pkey" PRIMARY KEY ("N_NATIONKEY"),
--  CONSTRAINT "NATION_N_REGIONKEY_fkey" FOREIGN KEY ("N_REGIONKEY")
--      REFERENCES "REGION" ("R_REGIONKEY") MATCH SIMPLE
--      ON UPDATE NO ACTION ON DELETE NO ACTION
)
WITH (OIDS=FALSE);

CREATE TABLE "CUSTOMER"
(
  "C_CUSTKEY" integer NOT NULL,
  "C_NAME" character varying(25),
  "C_ADDRESS" character varying(40),
  "C_NATIONKEY" integer,
  "C_PHONE" character(15),
  "C_ACCTBAL" double precision,
  "C_MKTSEGMENT" character(10),
  "C_COMMENT" character varying(117)
--  CONSTRAINT "CUSTOMER_pkey" PRIMARY KEY ("C_CUSTKEY"),
--  CONSTRAINT "CUSTOMER_C_NATIONKEY_fkey" FOREIGN KEY ("C_NATIONKEY")
--      REFERENCES "NATION" ("N_NATIONKEY") MATCH SIMPLE
--      ON UPDATE NO ACTION ON DELETE NO ACTION
)
WITH (OIDS=FALSE);

CREATE TABLE "PART"
(
  "P_PARTKEY" integer NOT NULL,
  "P_NAME" character varying(55),
  "P_MFGR" character(25),
  "P_BRAND" character(10),
  "P_TYPE" character varying(25),
  "P_SIZE" integer,
  "P_CONTAINER" character(10),
  "P_RETAILPRICE" double precision,
  "P_COMMENT" character varying(23)
--  CONSTRAINT "PART_pkey" PRIMARY KEY ("P_PARTKEY")
)
WITH (OIDS=FALSE);

CREATE TABLE "SUPPLIER"
(
  "S_SUPPKEY" integer NOT NULL,
  "S_NAME" character(25),
  "S_ADDRESS" character varying(40),
  "S_NATIONKEY" integer,
  "S_PHONE" character(15),
  "S_ACCTBAL" double precision,
  "S_COMMENT" character varying(101)
--  CONSTRAINT "SUPPLIER_pkey" PRIMARY KEY ("S_SUPPKEY"),
--  CONSTRAINT "SUPPLIER_S_NATIONKEY_fkey" FOREIGN KEY ("S_NATIONKEY")
--      REFERENCES "NATION" ("N_NATIONKEY") MATCH SIMPLE
--      ON UPDATE NO ACTION ON DELETE NO ACTION
)
WITH (OIDS=FALSE);

CREATE TABLE "PARTSUPP"
(
  "PS_PARTKEY" integer NOT NULL,
  "PS_SUPPKEY" integer NOT NULL,
  "PS_AVAILQTY" integer,
  "PS_SUPPLYCOST" double precision,
  "PS_COMMENT" character varying(199)
--  CONSTRAINT "PARTSUPP_pkey" PRIMARY KEY ("PS_PARTKEY", "PS_SUPPKEY"),
--  CONSTRAINT "PARTSUPP_PS_PARTKEY_fkey" FOREIGN KEY ("PS_PARTKEY")
--      REFERENCES "PART" ("P_PARTKEY") MATCH SIMPLE
--      ON UPDATE NO ACTION ON DELETE NO ACTION,
--  CONSTRAINT "PARTSUPP_PS_SUPPKEY_fkey" FOREIGN KEY ("PS_SUPPKEY")
--      REFERENCES "SUPPLIER" ("S_SUPPKEY") MATCH SIMPLE
--      ON UPDATE NO ACTION ON DELETE NO ACTION
)
WITH (OIDS=FALSE);

CREATE TABLE "ORDERS"
(
  "O_ORDERKEY" integer NOT NULL,
  "O_CUSTKEY" integer,
  "O_ORDERSTATUS" character(1),
  "O_TOTALPRICE" double precision,
  "O_ORDERDATE" date,
  "O_ORDERPRIORITY" character(15),
  "O_CLERK" character(15),
  "O_SHIPPRIORITY" integer,
  "O_COMMENT" character varying(79)
--  CONSTRAINT "ORDERS_pkey" PRIMARY KEY ("O_ORDERKEY"),
--  CONSTRAINT "ORDERS_O_CUSTKEY_fkey" FOREIGN KEY ("O_CUSTKEY")
--      REFERENCES "CUSTOMER" ("C_CUSTKEY") MATCH SIMPLE
--      ON UPDATE NO ACTION ON DELETE NO ACTION
)
WITH (OIDS=FALSE);

CREATE TABLE "LINEITEM"
(
  "L_ORDERKEY" integer NOT NULL,
  "L_PARTKEY" integer,
  "L_SUPPKEY" integer,
  "L_LINENUMBER" integer NOT NULL,
  "L_QUANTITY" double precision,
  "L_EXTENDEDPRICE" double precision,
  "L_DISCOUNT" double precision,
  "L_TAX" double precision,
  "L_RETURNFLAG" character(1),
  "L_LINESTATUS" character(1),
  "L_SHIPDATE" date,
  "L_COMMITDATE" date,
  "L_RECEIPTDATE" date,
  "L_SHIPINSTRUCT" character(25),
  "L_SHIPMODE" character(10),
  "L_COMMENT" character varying(44)
--  CONSTRAINT "LINEITEM_pkey" PRIMARY KEY ("L_ORDERKEY", "L_LINENUMBER"),
--  CONSTRAINT "LINEITEM_L_ORDERKEY_fkey" FOREIGN KEY ("L_ORDERKEY")
--      REFERENCES "ORDERS" ("O_ORDERKEY") MATCH SIMPLE
--      ON UPDATE NO ACTION ON DELETE NO ACTION,
--  CONSTRAINT "LINEITEM_L_PARTKEY_fkey" FOREIGN KEY ("L_PARTKEY", "L_SUPPKEY")
--      REFERENCES "PARTSUPP" ("PS_PARTKEY", "PS_SUPPKEY") MATCH SIMPLE
--      ON UPDATE NO ACTION ON DELETE NO ACTION
)
WITH (OIDS=FALSE);

COPY "REGION" ( "R_REGIONKEY", "R_NAME", "R_COMMENT" )
  FROM '/Users/xthemage/Documents/Projects/Applications/tpch_2_8_0/sample_set/data/region.notail.tbl' WITH DELIMITER '|';

COPY "NATION" ( "N_NATIONKEY", "N_NAME", "N_REGIONKEY", "N_COMMENT" )
  FROM '/Users/xthemage/Documents/Projects/Applications/tpch_2_8_0/sample_set/data/nation.notail.tbl' WITH DELIMITER '|';

COPY "CUSTOMER"("C_CUSTKEY", "C_NAME", "C_ADDRESS", "C_NATIONKEY", "C_PHONE", "C_ACCTBAL", "C_MKTSEGMENT", "C_COMMENT")
  FROM '/Users/xthemage/Documents/Projects/Applications/tpch_2_8_0/sample_set/data/customer.notail.tbl' WITH DELIMITER '|';

COPY "SUPPLIER" ( "S_SUPPKEY", "S_NAME", "S_ADDRESS", "S_NATIONKEY", "S_PHONE", "S_ACCTBAL", "S_COMMENT" )
  FROM '/Users/xthemage/Documents/Projects/Applications/tpch_2_8_0/sample_set/data/supplier.notail.tbl' WITH DELIMITER '|';

COPY "PART" ( "P_PARTKEY", "P_NAME", "P_MFGR", "P_BRAND", "P_TYPE", "P_SIZE", "P_CONTAINER", "P_RETAILPRICE", "P_COMMENT" )
  FROM '/Users/xthemage/Documents/Projects/Applications/tpch_2_8_0/sample_set/data/part.notail.tbl' WITH DELIMITER '|';

COPY "PARTSUPP" ( "PS_PARTKEY", "PS_SUPPKEY", "PS_AVAILQTY", "PS_SUPPLYCOST", "PS_COMMENT" )
  FROM '/Users/xthemage/Documents/Projects/Applications/tpch_2_8_0/sample_set/data/partsupp.notail.tbl' WITH DELIMITER '|';

COPY "ORDERS" ( "O_ORDERKEY", "O_CUSTKEY", "O_ORDERSTATUS", "O_TOTALPRICE", "O_ORDERDATE", "O_ORDERPRIORITY", "O_CLERK", "O_SHIPPRIORITY", "O_COMMENT" ) 
  FROM '/Users/xthemage/Documents/Projects/Applications/tpch_2_8_0/sample_set/data/orders.notail.tbl' WITH DELIMITER '|';
  
COPY "LINEITEM" ( "L_ORDERKEY", "L_PARTKEY", "L_SUPPKEY", "L_LINENUMBER", "L_QUANTITY", "L_EXTENDEDPRICE", "L_DISCOUNT", "L_TAX", "L_RETURNFLAG", "L_LINESTATUS", "L_SHIPDATE", "L_COMMITDATE", "L_RECEIPTDATE", "L_SHIPINSTRUCT", "L_SHIPMODE", "L_COMMENT" ) 
  FROM '/Users/xthemage/Documents/Projects/Applications/tpch_2_8_0/sample_set/data/lineitem.notail.tbl' WITH DELIMITER '|';


ALTER TABLE REGION ADD CONSTRAINT "REGION_pkey" PRIMARY KEY ("R_REGIONKEY");
ALTER TABLE "REGION" ADD CONSTRAINT "REGION_pkey" PRIMARY KEY ("R_REGIONKEY");
ALTER TABLE "NATION" ADD CONSTRAINT "NATION_pkey" PRIMARY KEY ("N_NATIONKEY");
ALTER TABLE "NATION" ADD CONSTRAINT "NATION_N_REGIONKEY_fkey" FOREIGN KEY ("N_REGIONKEY") REFERENCES "REGION" ("R_REGIONKEY");
ALTER TABLE "CUSTOMER" ADD CONSTRAINT "CUSTOMER_pkey" PRIMARY KEY ("C_CUSTKEY");
ALTER TABLE "CUSTOMER" ADD CONSTRAINT "CUSTOMER_C_NATIONKEY_fkey" FOREIGN KEY ("C_NATIONKEY") REFERENCES "NATION" ("N_NATIONKEY");
ALTER TABLE "PART" ADD CONSTRAINT "PART_pkey" PRIMARY KEY ("P_PARTKEY");
ALTER TABLE "SUPPLIER" ADD CONSTRAINT "SUPPLIER_pkey" PRIMARY KEY ("S_SUPPKEY");
ALTER TABLE "SUPPLIER" ADD CONSTRAINT "SUPPLIER_S_NATIONKEY_fkey" FOREIGN KEY ("S_NATIONKEY") REFERENCES "NATION"("N_NATIONKEY");
ALTER TABLE "PARTSUPP" ADD CONSTRAINT "PARTSUPP_pkey" PRIMARY KEY ("PS_PARTKEY", "PS_SUPPKEY");
ALTER TABLE "PARTSUPP" ADD CONSTRAINT "PARTSUPP_PS_PARTKEY_fkey" FOREIGN KEY ("PS_PARTKEY") REFERENCES "PART" ("P_PARTKEY");
ALTER TABLE "PARTSUPP" ADD CONSTRAINT "PARTSUPP_PS_SUPPKEY_fkey" FOREIGN KEY ("PS_SUPPKEY") REFERENCES "SUPPLIER" ("S_SUPPKEY");
ALTER TABLE "ORDERS" ADD CONSTRAINT "ORDERS_pkey" PRIMARY KEY ("O_ORDERKEY");
ALTER TABLE "ORDERS" ADD CONSTRAINT "ORDERS_O_CUSTKEY_fkey" FOREIGN KEY ("O_CUSTKEY") REFERENCES "CUSTOMER" ("C_CUSTKEY");
ALTER TABLE "LINEITEM" ADD CONSTRAINT "LINEITEM_pkey" PRIMARY KEY ("L_ORDERKEY", "L_LINENUMBER");
ALTER TABLE "LINEITEM" ADD CONSTRAINT "LINEITEM_L_ORDERKEY_fkey" FOREIGN KEY ("L_ORDERKEY") REFERENCES "ORDERS" ("O_ORDERKEY");
ALTER TABLE "LINEITEM" ADD CONSTRAINT "LINEITEM_L_PARTKEY_fkey" FOREIGN KEY ("L_PARTKEY", "L_SUPPKEY") REFERENCES "PARTSUPP" ("PS_PARTKEY", "PS_SUPPKEY");






