#!/bin/bash

BASEDIR=`dirname $0`
LAUNCHERS=$BASEDIR/launchers.list

for i in $(awk '{print $1}' $LAUNCHERS); do
if [ "bin/$2.$i.sh" -ot "$0" -o "bin/$2.$i.sh" -ot "$LAUNCHERS" ] ; then
echo Creating bin/$i.sh

FORMAT=$(grep "^$i" $LAUNCHERS | awk '{print $3}');

if [ "$FORMAT" = "java" ] ; then 
EXEC_STRING="java -Xms256m -Xmx1025m -server -Djruby.compile.mode=FORCE -Djruby.compile.fastest=true -cp --CLASSPATH-- --CLASS-- \$(dirname \$0)/../local.properties \$*"
elif [ "$FORMAT" = "java-prof" ] ; then 
EXEC_STRING="java -Xms256m -Xmx1025m  -Xrunhprof:cpu=samples,file=\$(basename \$0 .sh)_\$(hostname),thread=y -cp --CLASSPATH-- --CLASS-- \$(dirname \$0)/../local.properties \$*"
elif [ "$FORMAT" = "jruby" ] ; then 
EXEC_STRING="jruby -J-cp src/ruby:--CLASSPATH-- -e \"include Java;\\\$launcherClass='--CLASS--';require 'tools/launcher_init';require '--CLASS--';\" -- \$(dirname \$0)/../local.properties \$*"
fi

EXEC_CMD=$(echo "$EXEC_STRING" | 
  sed "
    s#--CLASSPATH--#$1#g; 
    s#--CLASS--#$(grep "^$i" $LAUNCHERS | awk '{print $2}')#g;
  ");
cat > bin/$i.sh << EOF
################# BEGIN AUTOGENERATED LAUNCHER SCRIPT #################
#echo ========================
#echo "$(echo $EXEC_CMD | sed 's#"#\\"#g' | cat)"
#echo ========================
$EXEC_CMD
################# END AUTOGENERATED LAUNCHER SCRIPT #################
EOF
chmod +x bin/$i.sh
cp bin/$i.sh bin/$2.$i.sh
fi
done