open UnitTest
open Calculus

let get_schema expr = 
   let ivars,ovars = 
      Calculus.schema_of_expr (parse_calc expr)
   in
      print_string (ListExtras.ocaml_of_list fst ivars);
      print_endline (ListExtras.ocaml_of_list fst ovars);
      print_string "\n"
;;

(*get_schema "
(delta_144 ^= ((AggSum([],(((delta_143 ^= ([-1] * [query18_mLINEITEMLINEITEM_QUANTITY])) * ((__sql_agg_tmp_1 ^= (AggSum([O_ORDERKEY],((LINEITEM(O_ORDERKEY, L3_QUANTITY) * [L3_QUANTITY]))) + [delta_143])) + ((__sql_agg_tmp_1 ^= AggSum([O_ORDERKEY],((LINEITEM(O_ORDERKEY, L3_QUANTITY) * [L3_QUANTITY])))) * [-1])) * [100 < __sql_agg_tmp_1]))) * AggSum([O_ORDERKEY],(LINEITEM(O_ORDERKEY, L2_QUANTITY)))) + ((AggSum([O_ORDERKEY],(((__sql_agg_tmp_1 ^= AggSum([O_ORDERKEY],((LINEITEM(O_ORDERKEY, L3_QUANTITY) * [L3_QUANTITY])))) * [100 < __sql_agg_tmp_1]))) + ((O_ORDERKEY ^= [query18_mLINEITEMLINEITEM_ORDERKEY]) * AggSum([],(((delta_139 ^= ([-1] * [query18_mLINEITEMLINEITEM_QUANTITY])) * ((__sql_agg_tmp_1 ^= (AggSum([O_ORDERKEY],((LINEITEM(O_ORDERKEY, L3_QUANTITY) * [L3_QUANTITY]))) + [delta_139])) + ((__sql_agg_tmp_1 ^= AggSum([O_ORDERKEY],((LINEITEM(O_ORDERKEY, L3_QUANTITY) * [L3_QUANTITY])))) * [-1])) * [100 < __sql_agg_tmp_1]))))) * [-1])))";;*)

(*get_schema "
(((delta_144 ^= ((AggSum([],(((delta_143 ^= ([-1] * [query18_mLINEITEMLINEITEM_QUANTITY])) * ((__sql_agg_tmp_1 ^= (AggSum([O_ORDERKEY],((LINEITEM(O_ORDERKEY, L3_QUANTITY) * [L3_QUANTITY]))) + [delta_143])) + ((__sql_agg_tmp_1 ^= AggSum([O_ORDERKEY],((LINEITEM(O_ORDERKEY, L3_QUANTITY) * [L3_QUANTITY])))) * [-1])) * [100 < __sql_agg_tmp_1]))) * AggSum([O_ORDERKEY],(LINEITEM(O_ORDERKEY, L2_QUANTITY)))) + ((AggSum([O_ORDERKEY],(((__sql_agg_tmp_1 ^= AggSum([O_ORDERKEY],((LINEITEM(O_ORDERKEY, L3_QUANTITY) * [L3_QUANTITY])))) * [100 < __sql_agg_tmp_1]))) + ((O_ORDERKEY ^= [query18_mLINEITEMLINEITEM_ORDERKEY]) * AggSum([],(((delta_139 ^= ([-1] * [query18_mLINEITEMLINEITEM_QUANTITY])) * ((__sql_agg_tmp_1 ^= (AggSum([O_ORDERKEY],((LINEITEM(O_ORDERKEY, L3_QUANTITY) * [L3_QUANTITY]))) + [delta_139])) + ((__sql_agg_tmp_1 ^= AggSum([O_ORDERKEY],((LINEITEM(O_ORDERKEY, L3_QUANTITY) * [L3_QUANTITY])))) * [-1])) * [100 < __sql_agg_tmp_1]))))) * [-1]))) * ((__sql_agg_tmp_2 ^= ((AggSum([O_ORDERKEY],(((__sql_agg_tmp_1 ^= AggSum([O_ORDERKEY],((LINEITEM(O_ORDERKEY, L3_QUANTITY) * [L3_QUANTITY])))) * [100 < __sql_agg_tmp_1]))) * AggSum([O_ORDERKEY],(LINEITEM(O_ORDERKEY, L2_QUANTITY)))) + [delta_144])) + ((__sql_agg_tmp_2 ^= (AggSum([O_ORDERKEY],(((__sql_agg_tmp_1 ^= AggSum([O_ORDERKEY],((LINEITEM(O_ORDERKEY, L3_QUANTITY) * [L3_QUANTITY])))) * [100 < __sql_agg_tmp_1]))) * AggSum([O_ORDERKEY],(LINEITEM(O_ORDERKEY, L2_QUANTITY))))) * [-1])) * [1 <= __sql_agg_tmp_2]))
";;*)

(*get_schema "(AggSum([],(((delta_143 ^= ([-1] * [query18_mLINEITEMLINEITEM_QUANTITY])) * ((__sql_agg_tmp_1 ^= (AggSum([query18_mLINEITEMLINEITEM_ORDERKEY],((LINEITEM(query18_mLINEITEMLINEITEM_ORDERKEY, L3_QUANTITY) * [L3_QUANTITY]))) + [delta_143])) + ((__sql_agg_tmp_1 ^= AggSum([query18_mLINEITEMLINEITEM_ORDERKEY],((LINEITEM(query18_mLINEITEMLINEITEM_ORDERKEY, L3_QUANTITY) * [L3_QUANTITY])))) * [-1])) * [100 < __sql_agg_tmp_1]))) * AggSum([query18_mLINEITEMLINEITEM_ORDERKEY],(LINEITEM(query18_mLINEITEMLINEITEM_ORDERKEY, L2_QUANTITY))))";;*)

get_schema "AggSum([query18_mLINEITEMLINEITEM_ORDERKEY],(((__sql_agg_tmp_1 ^= AggSum([query18_mLINEITEMLINEITEM_ORDERKEY],((LINEITEM(query18_mLINEITEMLINEITEM_ORDERKEY, L3_QUANTITY) * [L3_QUANTITY])))) * [100 < __sql_agg_tmp_1])))";;
get_schema "AggSum([],(((delta_139 ^= ([-1] * [query18_mLINEITEMLINEITEM_QUANTITY])) * ((__sql_agg_tmp_1 ^= (AggSum([query18_mLINEITEMLINEITEM_ORDERKEY],((LINEITEM(query18_mLINEITEMLINEITEM_ORDERKEY, L3_QUANTITY) * [L3_QUANTITY]))) + [delta_139])) + ((__sql_agg_tmp_1 ^= AggSum([query18_mLINEITEMLINEITEM_ORDERKEY],((LINEITEM(query18_mLINEITEMLINEITEM_ORDERKEY, L3_QUANTITY) * [L3_QUANTITY])))) * [-1])) * [100 < __sql_agg_tmp_1])))";;

get_schema "((AggSum([query18_mLINEITEMLINEITEM_ORDERKEY],(((__sql_agg_tmp_1 ^= AggSum([query18_mLINEITEMLINEITEM_ORDERKEY],((LINEITEM(query18_mLINEITEMLINEITEM_ORDERKEY, L3_QUANTITY) * [L3_QUANTITY])))) * [100 < __sql_agg_tmp_1]))) + AggSum([],(((delta_139 ^= ([-1] * [query18_mLINEITEMLINEITEM_QUANTITY])) * ((__sql_agg_tmp_1 ^= (AggSum([query18_mLINEITEMLINEITEM_ORDERKEY],((LINEITEM(query18_mLINEITEMLINEITEM_ORDERKEY, L3_QUANTITY) * [L3_QUANTITY]))) + [delta_139])) + ((__sql_agg_tmp_1 ^= AggSum([query18_mLINEITEMLINEITEM_ORDERKEY],((LINEITEM(query18_mLINEITEMLINEITEM_ORDERKEY, L3_QUANTITY) * [L3_QUANTITY])))) * [-1])) * [100 < __sql_agg_tmp_1])))) * [-1])";;


get_schema "
(delta_144 ^= ((AggSum([],(((delta_143 ^= ([-1] * [query18_mLINEITEMLINEITEM_QUANTITY])) * ((__sql_agg_tmp_1 ^= (AggSum([query18_mLINEITEMLINEITEM_ORDERKEY],((LINEITEM(query18_mLINEITEMLINEITEM_ORDERKEY, L3_QUANTITY) * [L3_QUANTITY]))) + [delta_143])) + ((__sql_agg_tmp_1 ^= AggSum([query18_mLINEITEMLINEITEM_ORDERKEY],((LINEITEM(query18_mLINEITEMLINEITEM_ORDERKEY, L3_QUANTITY) * [L3_QUANTITY])))) * [-1])) * [100 < __sql_agg_tmp_1]))) * AggSum([query18_mLINEITEMLINEITEM_ORDERKEY],(LINEITEM(query18_mLINEITEMLINEITEM_ORDERKEY, L2_QUANTITY)))) + ((AggSum([query18_mLINEITEMLINEITEM_ORDERKEY],(((__sql_agg_tmp_1 ^= AggSum([query18_mLINEITEMLINEITEM_ORDERKEY],((LINEITEM(query18_mLINEITEMLINEITEM_ORDERKEY, L3_QUANTITY) * [L3_QUANTITY])))) * [100 < __sql_agg_tmp_1]))) + AggSum([],(((delta_139 ^= ([-1] * [query18_mLINEITEMLINEITEM_QUANTITY])) * ((__sql_agg_tmp_1 ^= (AggSum([query18_mLINEITEMLINEITEM_ORDERKEY],((LINEITEM(query18_mLINEITEMLINEITEM_ORDERKEY, L3_QUANTITY) * [L3_QUANTITY]))) + [delta_139])) + ((__sql_agg_tmp_1 ^= AggSum([query18_mLINEITEMLINEITEM_ORDERKEY],((LINEITEM(query18_mLINEITEMLINEITEM_ORDERKEY, L3_QUANTITY) * [L3_QUANTITY])))) * [-1])) * [100 < __sql_agg_tmp_1])))) * [-1])))
";;
(*get_schema "
   (((delta_144 ^= ((AggSum([],(((delta_143 ^= ([-1] * [query18_mLINEITEMLINEITEM_QUANTITY])) * ((__sql_agg_tmp_1 ^= (AggSum([query18_mLINEITEMLINEITEM_ORDERKEY],((LINEITEM(query18_mLINEITEMLINEITEM_ORDERKEY, L3_QUANTITY) * [L3_QUANTITY]))) + [delta_143])) + ((__sql_agg_tmp_1 ^= AggSum([query18_mLINEITEMLINEITEM_ORDERKEY],((LINEITEM(query18_mLINEITEMLINEITEM_ORDERKEY, L3_QUANTITY) * [L3_QUANTITY])))) * [-1])) * [100 < __sql_agg_tmp_1]))) * AggSum([query18_mLINEITEMLINEITEM_ORDERKEY],(LINEITEM(query18_mLINEITEMLINEITEM_ORDERKEY, L2_QUANTITY)))) + ((AggSum([query18_mLINEITEMLINEITEM_ORDERKEY],(((__sql_agg_tmp_1 ^= AggSum([query18_mLINEITEMLINEITEM_ORDERKEY],((LINEITEM(query18_mLINEITEMLINEITEM_ORDERKEY, L3_QUANTITY) * [L3_QUANTITY])))) * [100 < __sql_agg_tmp_1]))) + AggSum([],(((delta_139 ^= ([-1] * [query18_mLINEITEMLINEITEM_QUANTITY])) * ((__sql_agg_tmp_1 ^= (AggSum([query18_mLINEITEMLINEITEM_ORDERKEY],((LINEITEM(query18_mLINEITEMLINEITEM_ORDERKEY, L3_QUANTITY) * [L3_QUANTITY]))) + [delta_139])) + ((__sql_agg_tmp_1 ^= AggSum([query18_mLINEITEMLINEITEM_ORDERKEY],((LINEITEM(query18_mLINEITEMLINEITEM_ORDERKEY, L3_QUANTITY) * [L3_QUANTITY])))) * [-1])) * [100 < __sql_agg_tmp_1])))) * [-1]))) * ((__sql_agg_tmp_2 ^= ((AggSum([query18_mLINEITEMLINEITEM_ORDERKEY],(((__sql_agg_tmp_1 ^= AggSum([query18_mLINEITEMLINEITEM_ORDERKEY],((LINEITEM(query18_mLINEITEMLINEITEM_ORDERKEY, L3_QUANTITY) * [L3_QUANTITY])))) * [100 < __sql_agg_tmp_1]))) * AggSum([query18_mLINEITEMLINEITEM_ORDERKEY],(LINEITEM(query18_mLINEITEMLINEITEM_ORDERKEY, L2_QUANTITY)))) + [delta_144])) + ((__sql_agg_tmp_2 ^= (AggSum([query18_mLINEITEMLINEITEM_ORDERKEY],(((__sql_agg_tmp_1 ^= AggSum([query18_mLINEITEMLINEITEM_ORDERKEY],((LINEITEM(query18_mLINEITEMLINEITEM_ORDERKEY, L3_QUANTITY) * [L3_QUANTITY])))) * [100 < __sql_agg_tmp_1]))) * AggSum([query18_mLINEITEMLINEITEM_ORDERKEY],(LINEITEM(query18_mLINEITEMLINEITEM_ORDERKEY, L2_QUANTITY))))) * [-1])) * [1 <= __sql_agg_tmp_2]))
"*)