function createfigure(X1, Y1, X2, Y2)
%CREATEFIGURE(X1,Y1,X2,Y2)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data

%  Auto-generated by MATLAB on 14-Jun-2009 21:10:01

% Create figure
figure1 = figure('XVisual',...
    '0x24 (TrueColor, depth 24, RGB mask 0xff0000 0xff00 0x00ff)');

% Create axes
axes1 = axes('Parent',figure1,'YGrid','on',...
    'XTick',[0 2 4 6 8 10 12 14 16 18 20],...
    'XMinorGrid','on',...
    'XGrid','on',...
    'FontSize',16);
box('on');
hold('all');

% Create plot
plot(X1,Y1,'Parent',axes1,'MarkerFaceColor',[0.3922 0.4745 0.6353],...
    'MarkerSize',15,...
    'Marker','x',...
    'LineWidth',6,...
    'Color',[0.3922 0.4745 0.6353],...
    'DisplayName',' Naive compilation');

% Create plot
plot(X2,Y2,'Parent',axes1,'LineWidth',6,'Color',[0.8706 0.4902 0],...
    'DisplayName',' DBToaster');

% Create xlabel
xlabel('Query frequency (#queries per workload)','FontSize',20);

% Create ylabel
ylabel('Query execution time (secs)','FontSize',20);

% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','NorthWest');

