function createfigure(X1, Y1, X2, Y2)
%CREATEFIGURE(X1,Y1,X2,Y2)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data

%  Auto-generated by MATLAB on 14-Jun-2009 21:33:13

% Create figure
figure1 = figure('XVisual',...
    '0x24 (TrueColor, depth 24, RGB mask 0xff0000 0xff00 0x00ff)');

% Create axes
axes1 = axes('Parent',figure1,'Position',[0.13 0.1787 0.3293 0.7076],...
    'FontSize',16);
box('on');
hold('all');

% Create plot
plot(X1,Y1,'Parent',axes1,'Marker','x','LineStyle','none','Color',[0 0 0]);

% Create xlabel
xlabel('% workload processed','FontSize',20);

% Create ylabel
ylabel('Memory usage (bytes)','FontSize',20);

% Create axes
axes2 = axes('Parent',figure1,'Position',[0.5703 0.1805 0.3347 0.7058],...
    'FontSize',16);
box('on');
hold('all');

% Create plot
plot(X2,Y2,'Parent',axes2,'Marker','x','LineStyle','none','Color',[0 0 0]);

% Create xlabel
xlabel('% workload processed','FontSize',20);

% Create ylabel
ylabel('Memory usage (bytes)','FontSize',20);

% Create textbox
annotation(figure1,'textbox',[0.1911 -0.003866 0.2338 0.07581],...
    'String',{'VWAP query'},...
    'FontSize',20,...
    'EdgeColor','none');

% Create textbox
annotation(figure1,'textbox',[0.662 -0.003089 0.2032 0.07581],...
    'String',{'SSB query'},...
    'FontSize',20,...
    'EdgeColor','none');

