/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef query20_CONSTANTS_H
#define query20_CONSTANTS_H

#include "query20_types.h"

namespace DBToaster { namespace Viewer { namespace query20 {

class query20Constants {
 public:
  query20Constants();

};

extern const query20Constants g_query20_constants;

}}} // namespace

#endif
